# Generated by Django 5.0.7 on 2024-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spentAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
